delimiter: "§"
settings:
  disabledGroups:
  - admin
  WhitelistMode: true
  #Сколько может прожить информация об игроке в памяти.
  UpdateTime: 10 #в минутах

#В default ставится только цвет ника и цвет текста через ":".
#В группах ставится цвет ника, стоимость, цвет текста через ":".
default: "#CFCFCF:#545454"
groups:
  admin:
    test: "#ffffff:10:#cfcfcf"