hook:
  placeholderapi: true
  tab: true
  luckperms: true
  fastasyncworldedit: true
  itemsadder: true
  protocollib: true

settings:
  language: ru

modules:
  #Модуль полета при определенной броне.
  # - Совместим с плагином ItemsAdder
  shift-fly: false
  # - Материал либо id предмета из itemsadder'а (пример: "DIAMOND_HELMET, LEATHER_CHESTPLATE, ...").
  shift-fly-armor: "" #"Шлем, Нагрудник, Поножи, Ботинки".

  #Emoji tab-complete
  # - Для работы нужен плагин ProtocolLib
  emoji-taber: true

  #Модификация выстрела в голову
  headshot-modification: true

  #Tab-complete упоминаний игроков
  # - Для работы нужен плагин ProtocolLib
  #
  # Примечание: если у игрока ник ровно 16 символов,
  # то его упоминание будет недоступно!
  mention-taber: true
  mention-taber-symbol: "@"

  #Простой FFA режим
  ffa: false

  #Дает возможность спать утром и ночью.
  day-sleep: true

  #Улучшение зелья невидимости
  better-invisibility: false

  #Модификация ников
  # - Для работы нужен TAB плагин
  nickname: true
  color-nickname: true
  money-to-change-nickname-color: true

  #Модуль обновления файлов
  updater: false
  # - Меняйте только в том случае, если знаете что делаете.
  updater-ip: "127.0.0.1"
  updater-port: 3820

#MySQL. Если данные для подключения вписаны неправильно,
#то данные будут записываться в локальную базу данных.
mysql:
  enabled: false
  updateTime: 30 #минут
  prefix: 'br_'
  host: ''
  port: ''
  database: ''
  user: ''
  password: ''

debug: false
config-version: ""