settings:
  disabledGroups:
    - testgroup
    - Astroreen
  WhitelistMode: false

default: "#CCFFCC"
groups:
  testgroup:
    white: "#ffffff 10"
    gray: "#cfcfcf 100"
  Astroreen:
    black: "#000000 1000"