settings:
  disabledGroups:
    - testgroup
    - Astroreen
  WhitelistMode: false
  #Сколько может прожить информация об игроке в памяти.
  UpdateTime: 10 #в минутах

default: "#CCFFCC"
groups:
  testgroup:
    white: "#ffffff 10"
    gray: "#cfcfcf 100"
  Astroreen:
    black: "#000000 1000"