hook:
  placeholderapi: true
  tab: true

settings:
  language: ru
  modules:
    tab:
      ColorNickname: true
      UseMoney: true
    updater: true

#MySQL. Если данные для подключения вписаны неправильно,
#то данные будут записываться в локальную базу данных.
mysql:
  enabled: false
  updateTime: 30 #минут
  prefix: 'br_'
  host: ''
  port: ''
  database: ''
  user: ''
  password: ''

debug: false