hook:
  placeholderapi: true
  tab: true
  luckperms: true
  fastasyncworldedit: true
  itemsadder: true
  protocollib: true

settings:
  language: ru
  modules:
    emoji-taber:
      enabled: true
    mention-taber:
      enabled: true
      symbol: "@"
    ffa:
      enabled: false
    tab:
      enabled: true
      ColorNickname: true
      UseMoney: true
    updater:
      enabled: false
      #Меняйте только в том случае, если знаете что делаете.
      ip: "127.0.0.1"
      port: 3820

#MySQL. Если данные для подключения вписаны неправильно,
#то данные будут записываться в локальную базу данных.
mysql:
  enabled: false
  updateTime: 30 #минут
  prefix: 'br_'
  host: ''
  port: ''
  database: ''
  user: ''
  password: ''

debug: false