#Создать отдельную папку для хранения схематиков
#или пользоваться стандартной?
use-different-schematic-folder: false

#Впишите сюда название миров которые будут считаться за арены.
#А также укажите какой схематик для них использовать.
#Если плагин WorldEdit или сам схематик отсутствует, то арена не
#будет обновляться при завершении игры.
#Если укажите "none", то арена тоже не будет обновляться.
#Создав несуществующую арену, она создастся как пустой мир.
arenas:
  exampleworldname: #Название арены
    use: false #Использовать эту арену?
    schematic: "none" #Используемый схематик. Пример: "random-schematic.schem".
    schematic-cords: "0:70:0" #На какой блок поставить схематик (x, y, z).
    schematic-restart: 30 #Через сколько восстановить арену (в минутах).

    #Телепорт по локациям.
    #Вы можете самостоятельно вписывать названия для новых точек телепорта.
    default-pos: "0.0, 1.0, 0.0" #Начальная точка если телепорт выключен.
    teleport:
      enabled: false
      rtp-enabled: true #Разрешить рандомный телепорт по локациям.
      bee-dim: "0.0, 0.0, 0.0" #Это новая точка телепорта.