#Впишите сюда название миров которые будут считаться за арены.
#А также укажите какой схематик для них использовать.
#Если плагин WorldEdit или сам схематик отсутствует, то арена не
#будет обновляться при завершении игры.
#Если укажите "none", то арена тоже не будет обновляться.
arenas:
  world:
    use: false
    schematic: "none" #пример: "random-schematic.schem".
    schematic-cords: "0:70:0" #По каким координатам вставлять схематик (x, y, z).

    #Телепорт по локациям.
    #Вы можете самостоятельно вписывать названия для новых точек телепорта.
    default-pos: "0.0, 1.0, 0.0" #начальная точка если телепорт выключен.
    teleport:
      enabled: false
      rtp-enabled: true #разрешить рандомный телепорт по локациям.
      bee-dim: "0.0, 0.0, 0.0" #Это новая точка телепорта.